# Cloud Build configuration for automated deployment
# This file is used for CI/CD deployment of the Cloud Function
#
# Usage:
#   gcloud builds submit --config=cloudbuild.yaml
#
# Or set up a trigger to auto-deploy on git push

steps:
- id: Deploy-Function
  name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args:
    - -c
    - |
      gcloud functions deploy fetchFbAdsToBigQuery \
        --gen2 \
        --region=us-central1 \
        --runtime=python313 \
        --entry-point=main \
        --trigger-topic=fb-ads-topic \
        --set-env-vars=GCP_PROJECT=YOUR_PROJECT,BQ_TABLE=YOUR_DATASET.ad_data \
        --timeout=300 \
        --memory=256MB
